{{- $conf := index .Values .Values.global.env -}}
{{- $def := index .Values "default" -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ template "gateway-service.fullname" . }}-gateway
  labels:
    app: {{ template "gateway-service.name" . }}
    chart: {{ template "gateway-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "{{ default $def.ext_hostname $conf.ext_hostname }}"
    tls:
      httpsRedirect: true # sends 301 redirect for http requests
  - port:
      number: 443
      name: https-443
      protocol: HTTPS
    hosts:
    - "{{ default $def.ext_hostname $conf.ext_hostname }}"
    tls:
      mode: SIMPLE # enables HTTPS on this port
      credentialName: "{{ default $def.tls_secret_name $conf.tls_secret_name }}"  # fetches certs from Kubernetes secret      
